name: 07 Basics Conditions

on: 
  pull_request:
    types: 
      - closed

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    # if: ${{ github.event.pull_request.merged == true }}
    if: github.event.pull_request.merged == true
    
    # or this syntax
    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: Print Conditional Message
        if: github.event.pull_request.changed_files > 1
        run: echo "This pull request has multiple file changes"